# Generated by Django 4.2.13 on 2024-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_route_axle_load_route_end_points_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_points_x',
            field=models.CharField(max_length=120, verbose_name='Координаты города прибытия x'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_points_y',
            field=models.CharField(max_length=120, verbose_name='Координаты города прибытия y'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_points_x',
            field=models.CharField(max_length=120, verbose_name='Координаты города отправки x'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_points_y',
            field=models.CharField(max_length=120, verbose_name='Координаты города отправки y'),
        ),
    ]
