# Generated by Django 4.2.13 on 2024-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_alter_route_options_gasstation_height_above_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_title',
            field=models.TextField(blank=True, null=True, verbose_name='Название прибытия маршрута'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_title',
            field=models.TextField(blank=True, null=True, verbose_name='Название отправления маршрута'),
        ),
    ]
