# Generated by Django 4.2.13 on 2024-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_route_end_title_route_start_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='status_jams',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Учитывать пробки'),
        ),
    ]
